### ISSUE TITLE
Website User-Login View in iPad Pro 11 inch quite weird

### ISSUE THREAD

**Issue by Apiphoom** [api-development/Playsound-Web-Design-Unreleased#2]
Please fix it
![IMG_0306](https://user-images.githubusercontent.com/48949523/87126950-4aebea00-c2b7-11ea-9213-a46480dec54d.PNG)

**Comment by Kentakoong** [comment]
how is it wierd

**Comment by Apiphoom** [comment]
look at the "welcome" Label

**Comment by Apiphoom** [comment]
@Kentakoong
